/**
 * Supabase database types — auto-generated by:
 * npx supabase gen types typescript --local > src/types/database.ts
 *
 * DO NOT edit manually. Run `npm run db:types` to regenerate.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
