/**
 * Global TypeScript types for PadelOS.
 * DB types are auto-generated — see database.ts (generated by Supabase CLI).
 */

// ─── Role & Auth ────────────────────────────────────────────────────────────

export type UserRole =
  | 'super_admin'
  | 'federation_admin'
  | 'club_admin'
  | 'referee'
  | 'player'

export type OrgType = 'federation' | 'club' | 'league'

// ─── Tournament ──────────────────────────────────────────────────────────────

export type TournamentCategory =
  | 'M25' | 'M50' | 'M100' | 'M250' | 'M500' | 'M1000'
  | 'W25' | 'W50' | 'W100' | 'W250' | 'W500' | 'W1000'
  | 'JUNIOR_U11' | 'JUNIOR_U13' | 'JUNIOR_U15'

export type TournamentGender = 'men' | 'women' | 'mixed'

export type TournamentStatus =
  | 'draft'
  | 'registration'
  | 'active'
  | 'completed'
  | 'cancelled'

export type MatchPhase = 'qualification' | 'main'

export type MatchRound = 'GROUP' | 'R64' | 'R32' | 'R16' | 'QF' | 'SF' | 'F'

export type MatchStatus = 'pending' | 'in_progress' | 'completed' | 'walkover'

export type EntryStatus = 'registered' | 'confirmed' | 'withdrawn' | 'disqualified'

// ─── Match Formats ───────────────────────────────────────────────────────────

export type MatchFormat = 'FORMAT_A' | 'FORMAT_B' | 'FORMAT_C' | 'FORMAT_D'

export interface SetScore {
  e1: number
  e2: number
}

export interface TiebreakScore {
  e1: number
  e2: number
}

export interface MatchScore {
  sets: SetScore[]
  tb?: TiebreakScore // super tiebreak
  serving?: 'e1' | 'e2' | null
}

// ─── Rankings ────────────────────────────────────────────────────────────────

export type RankingRound = 'W' | 'SF' | 'QF' | 'R16' | 'R32' | 'R64' | 'QG'

export interface FIPRankingResult {
  playerId: string
  totalPoints: number
  best8Points: number
  countedTournaments: string[] // tournament IDs
}

// ─── Subscription ────────────────────────────────────────────────────────────

export type SubscriptionPlan = 'STARTER' | 'CLUB_PRO' | 'FEDERATION'

export type SubscriptionStatus =
  | 'active'
  | 'trialing'
  | 'past_due'
  | 'cancelled'

// ─── API Responses ───────────────────────────────────────────────────────────

export interface ApiError {
  code: string
  message: string
}

export interface ApiSuccess<T> {
  data: T
  message?: string
}

// ─── UI ──────────────────────────────────────────────────────────────────────

export interface NavItem {
  label: string
  href: string
  icon?: React.ComponentType<{ className?: string }>
  badge?: string
}
